### ISSUE TITLE
Something wrong with bcrypt

### ISSUE THREAD

**Issue by kanishkabodaragama** [kanishkabodaragama/Hotel-Booking-System#1]
Error: Illegal arguments: undefined, string
    at _async (G:\PROJECTS\MERN STACK\BOOKING\api\node_modules\bcryptjs\dist\bcrypt.js:286:46)
    at G:\PROJECTS\MERN STACK\BOOKING\api\node_modules\bcryptjs\dist\bcrypt.js:307:17
    at new Promise (<anonymous>)
    at bcrypt.compare (G:\PROJECTS\MERN STACK\BOOKING\api\node_modules\bcryptjs\dist\bcrypt.js:306:20)
    at login (file:///G:/PROJECTS/MERN%20STACK/BOOKING/api/controllers/auth.js:29:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by kanishkabodaragama** [comment]
Fixed
